### ISSUE TITLE
python2 errors in ddrimport

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-cmdln#181]
Not all the old `basestring` and other python2 features got converted in the `ddrimport` and possibly other modules.

```
$ ddrimport entity -U REDACTED -P REDACTED  /media/qnfs/kinkura/working/ddr-testing-40366/ddr-testing-40366-objects.csv /media/qnfs/kinkura/gold/ddr-testing-40366 | tee -a /media/qnfs/kinkura/working/logs/ddrimport_ddr-testing-40366-entities.log
 File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/cli/ddrimport.py", line 161, in entity
    csv_path, ci, config.VOCABS_URL, idservice_client
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/cli/ddrimport.py", line 286, in run_checks
    chkcsv = batch.Checker.check_csv(csv_path, ci, vocabs_url)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/batch.py", line 237, in check_csv
    module, vocabs, headers, rowds, model
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/batch.py", line 440, in _validate_csv_file
    rowds_errs = csvfile.validate_rowds(module, headers, required_fields, valid_values, rowds, find_dupes)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/csvfile.py", line
261, in validate_rowds
    invalid_values = find_invalid_values(module, headers, valid_values, rowds)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/csvfile.py", line
236, in find_invalid_values
    bad_fields = check_row_values(module, headers, valid_values, rowd)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/csvfile.py", line
169, in check_row_values
    [valid_values, value]
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/modules.py", line
112, in function
    value = function(value)
  File "/opt/ddr-defs/repo_models/entity.py", line 1424, in csvvalidate_topics
    def csvvalidate_topics( data ): return _validate_vocab_list('topics', data[0], data[1])
  File "/opt/ddr-defs/repo_models/entity.py", line 1401, in _validate_vocab_list
    if isinstance(datum, basestring):
NameError: name 'basestring' is not defined
```

**Comment by gjost** [comment]
Fixed in `ddr-defs` commit `229bc6a`.

**Comment by sarabeckman** [comment]
Still receiving this error when running `ddrimport` on ishigura. 
`(cmdln) ddr@ishigura:/media/qnfs/kinkura/working/ddr-testing-40366$ ddrimport entity -U sara.beckman -P b174ssBK /media/qnfs/kinkura/working/ddr-testing-40366/ddr-testing-40366-objects.csv /media/qnfs/kinkura/gold/ddr-testing-40366 | tee -a /media/qnfs/kinkura/working/logs/ddrimport_ddr-testing-40366-entities.log
2020-05-05 12:45:41,791 DEBUG    <DDR.identifier.Identifier collection:ddr-testing-40366>
2020-05-05 12:45:41,791 DEBUG    Username: sara.beckman
2020-05-05 12:45:41,791 DEBUG    Password: ********
2020-05-05 12:45:41,791 DEBUG    idservice.IDServiceClient.login(sara.beckman)
2020-05-05 12:45:41,794 DEBUG    Starting new HTTPS connection (1): idservice.densho.org:443
2020-05-05 12:45:42,070 DEBUG    https://idservice.densho.org:443 "POST /api/0.1/rest-auth/login/ HTTP/1.1" 200 50
2020-05-05 12:45:42,072 INFO     Checking CSV file
2020-05-05 12:45:42,073 INFO     5 rows
2020-05-05 12:45:42,073 DEBUG    Guessing model based on 5 rows
2020-05-05 12:45:42,074 DEBUG    model: entity
2020-05-05 12:45:42,075 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,095 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/index.json HTTP/1.1" 200 241
2020-05-05 12:45:42,134 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/facility.json
2020-05-05 12:45:42,140 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/genre.json
2020-05-05 12:45:42,142 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,144 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,146 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/public.json
2020-05-05 12:45:42,147 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/language.json
2020-05-05 12:45:42,150 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,154 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/format.json
2020-05-05 12:45:42,156 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/facility.json HTTP/1.1" 200 48090
2020-05-05 12:45:42,157 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/genre.json HTTP/1.1" 200 5348
2020-05-05 12:45:42,158 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,160 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,163 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/rights.json
2020-05-05 12:45:42,166 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/public.json HTTP/1.1" 200 302
2020-05-05 12:45:42,169 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,170 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/topics.json
2020-05-05 12:45:42,172 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/language.json HTTP/1.1" 200 1175
2020-05-05 12:45:42,173 INFO     getting vocab: http://partner.densho.org/vocab/api/0.2/status.json
2020-05-05 12:45:42,175 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/format.json HTTP/1.1" 200 715
2020-05-05 12:45:42,177 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,182 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/rights.json HTTP/1.1" 200 597
2020-05-05 12:45:42,184 DEBUG    Starting new HTTP connection (1): partner.densho.org:80
2020-05-05 12:45:42,189 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/status.json HTTP/1.1" 200 325
2020-05-05 12:45:42,198 DEBUG    http://partner.densho.org:80 "GET /vocab/api/0.2/topics.json HTTP/1.1" 200 526398
2020-05-05 12:45:42,357 INFO     Validating headers
2020-05-05 12:45:42,357 INFO     headers ok
2020-05-05 12:45:42,357 INFO     Validating rows
Traceback (most recent call last):
2020-05-05 12:45:42,357 INFO     Validating rows
Traceback (most recent call last):
  File "/opt/ddr-cmdln/venv/cmdln/bin/ddrimport", line 11, in <module>
    load_entry_point('ddr-cmdln==0.9.4b0', 'console_scripts', 'ddrimport')()
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click-7.1.1-py3.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/cli/ddrimport.py", line
161, in entity
    csv_path, ci, config.VOCABS_URL, idservice_client
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/cli/ddrimport.py", line
286, in run_checks
    chkcsv = batch.Checker.check_csv(csv_path, ci, vocabs_url)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/batch.py", line 237, in
check_csv
    module, vocabs, headers, rowds, model
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/batch.py", line 440, in
_validate_csv_file
    rowds_errs = csvfile.validate_rowds(module, headers, required_fields, valid_values, rowds, find_dupes)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/csvfile.py", line 261, in validate_rowds
    invalid_values = find_invalid_values(module, headers, valid_values, rowds)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/csvfile.py", line 236, in find_invalid_values
    bad_fields = check_row_values(module, headers, valid_values, rowd)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/csvfile.py", line 169, in check_row_values
    [valid_values, value]
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-0.9.4b0-py3.7.egg/DDR/modules.py", line 112, in function
    value = function(value)
  File "/opt/ddr-defs/repo_models/entity.py", line 1424, in csvvalidate_topics
    def csvvalidate_topics( data ): return _validate_vocab_list('topics', data[0], data[1])
  File "/opt/ddr-defs/repo_models/entity.py", line 1401, in _validate_vocab_list
    if isinstance(datum, basestring):
NameError: name 'basestring' is not defined`

**Comment by gjost** [comment]
This works on my end.  It looks like the error occurs in the `ddr-defs/repo_models/entity.py` file, which was updated in the last version.  Are you using an updated `ddr-defs`?

**Comment by sarabeckman** [comment]
Issues was that the config file in `/etc/ddr/ddrlocal-local.cfg` had the wrong path in `[cmdln] repo_models_path` in cmdln only VMs should have `[cmdln] repo_models_path=/opt/ddr-cmdln/ddr-defs/`

**Comment by gjost** [comment]
Note: This change was made in commit `6d6984f` and has been merged into the master branch.
